language: node_js
node_js:
- node
script:
- npm run coverage
env:
  global:
    secure: NXZoiV9nnAK2S3TNbDrrrd7SipAQucvGUrwB4tT1Q1Bfkfwi4iDxQX4/0t27GxYHKl5WjSZpY9UzmnAKu3rX/dxA1OEvhxbF73Iwq2NU8TbttS1Lq18U6NIzXXcUDp6iTDm7ramUU0qyWQ50DIQwrol5awKHuTYDAi5FDoJgu9FOHaj8z8NwEyMifBcxDl5UeMilKs7k7Y03IUZUBZGB+UXCmkoOoWLtjQNRnW39g3r+8rRucaDWq40yZxRxCH68qHAYvIG1eEHY+iSTcVRegRI2vvWNRxsqPN7tWluMuAaAv8+rbgQCcXKdi62n1Tlv9bWs0KqY5tr0qXACCBk7k5SHBdzr/bIqEXuYvyVdomDCjarBvnTgjseQNxKuVzcp9nIPMQHyx77f9T9EaPwQZXSItUbfB5uos3ttG61AmG4U0etvXgkcgHvFwtTR6nMy9EzioC34Ez8N38uMoTeEf2q74pbPxLgInyXxm5GM+37kitzZYUxE0KDp1d7qZSTAaHAGPWXK4gDMigaCeliCRSrBttEn/VurPoEq7MC23mod0/vlFaJiJP9/cC4TCOgNQzuYJCnlzl0DpxuULViw8CLL4qpyWy59rszkJbzrUrUOC1R1HOaXus5rapcxWkyFb4+oRTxJLhRyIOUhBgTIHXuuhTniUxLKf29jwDJsDtM=
